export const FORM_CHANGE = 'FORM_CHANGE';
export const SAVE_COMMENT = 'SAVE_COMMENT';
export const SAVE_COMMENT_FINISHED = 'SAVE_COMMENT_FINISHED';
export const NEW_COMMENT = 'NEW_COMMENT';
export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const RECEIVE_COMMENTS = 'RECEIVE_COMMENTS';
export const REQUEST_COMMENTS = 'REQUEST_COMMENTS';
export const SEARCH_COMMENTS = 'SEARCH_COMMENTS';